security:
  password_hasher:
    class: App\Entity\User
    algorithm: auto

  firewalls:
    login:
      pattern: ^/api/login
      stateless: true

    public_api:
      pattern: ^/api/products
      stateless: true

    orders_api:
      pattern: ^/api/orders
      stateless: true

    category_api:
      pattern: ^/api/categories
      stateless: true

    api:
      pattern: ^/api/
      stateless: true # Les requêtes API sont sans état (pas de session)
      jwt: ~ # Utiliser JWT pour l'authentification

  # Fournir un UserProvider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS } # Autoriser l'accès sans token
    - { path: ^/api/products, roles: PUBLIC_ACCESS }
    - { path: ^/api/orders, roles: PUBLIC_ACCESS }
    - { path: ^/api/categories, roles: PUBLIC_ACCESS }
    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY } # Toutes les autres routes API nécessitent un JWT valide
