version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - "8800:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    env_file:
      - .env.local
    links:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stone-jewelry
      MYSQL_USER: stone-jewelry
      MYSQL_PASSWORD: stone-pass
    volumes:
      - db_data2:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  db_data2:
